# Generated by Django 3.0.7 on 2020-06-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('qty', models.IntegerField(default=0)),
                ('image', models.ImageField(null=True, upload_to='media')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
