# Generated by Django 3.0.7 on 2020-06-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=500, null=True)),
                ('district', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('tax_office', models.CharField(max_length=50, null=True)),
                ('tax_no', models.CharField(max_length=50, null=True)),
                ('cell_number', models.CharField(max_length=15, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
